config/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('account/', include('account.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
    path('analysis/', include('analysis.urls')),
    path('trading_journal/',include('trading_journal.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

trading_journal/urls.py
from django.urls import path

from . import views

app_name = 'trading_journal'

urlpatterns = [
    path('', views.home, name='home'),
    path('<int:pk>/', views.trading_journal, name='trading_journal'),
    path('<int:pk>/create/', views.create_journal, name='create'),
]

home/models.py
from django.db import models

class EconomicCalendar(models.Model):
    scheduled_time = models.DateTimeField()
    contents = models.CharField(max_length=100)

    def __str__(self):
        return self.subject

class News(models.Model):
    post_date = models.DateTimeField()
    news_link = models.CharField(max_length=100,unique=True)
    title = models.CharField(max_length=100)
    img_link = models.CharField(max_length=100)

    def __str__(self):
        return self.subject

trading_journal/models.py
from django.db import models
from account.models import User

class TradingJournal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.DateField()
    content_1M = models.TextField(null=True, blank=True)
    content_1W = models.TextField(null=True, blank=True)
    content_1D = models.TextField(null=True, blank=True)
    content_4H = models.TextField(null=True, blank=True)
    content_1H = models.TextField(null=True, blank=True)
    content_15m = models.TextField(null=True, blank=True)

    img_1M = models.ImageField(upload_to='image/',null=True, blank=True)
    img_1W = models.ImageField(upload_to='image/',null=True, blank=True)
    img_1D = models.ImageField(upload_to='image/',null=True, blank=True)
    img_4H = models.ImageField(upload_to='image/',null=True, blank=True)
    img_1H = models.ImageField(upload_to='image/',null=True, blank=True)
    img_15m = models.ImageField(upload_to='image/',null=True, blank=True)

    transaction_content = models.TextField(null=True,blank=True)
    tp = models.TextField(null=True,blank=True)
    sl = models.TextField(null=True,blank=True)
    amount = models.TextField(null=True,blank=True)

    create_date = models.DateTimeField()

home/forms.py
from django import forms
from .models import EconomicCalendar, News

class EconomicCalendarForm(forms.ModelForm):
    class Meta:
        model = EconomicCalendar
        fields = ['scheduled_time','contents']

class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['post_date','news_link','title','img_link']

home/views.py
from django.shortcuts import render

from .forms import EconomicCalendarForm, NewsForm
from .models import EconomicCalendar, News
from datetime import datetime, timedelta, time
from dateutil.relativedelta import *
import pprint

# Create your views here.
def economic_information():
    today = datetime.now().date()
    #data = EconomicCalendar.objects.values().all()
    monday = today + relativedelta(weekday=MO(-1))
    data = EconomicCalendar.objects.filter(scheduled_time__range=(monday,monday+timedelta(days=7))).values().all()
    week = [monday+timedelta(i) for i in range(7)]

    news = News.objects.all().order_by('-post_date').filter(post_date__range=(today,today+timedelta(days=1))).values()

    context = {
        'calendar_lists': data,
        'week': week,
        'today': today,
        'news': news,
    }
    return context

def index(request):
    context = economic_information()

    return render(request, 'home/home.html', context)

trading_journal/views.py
from django.shortcuts import render
from django.http import HttpResponseNotAllowed
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

def home(request):
    return render(request, 'trading_journal/home.html')

def trading_journal(request,pk):

    return render(request, 'trading_journal/trading_journal.html')

def create_journal(request,pk):
    currency = None
    symbol = None
    analysis_time = None
    if request.method == "POST":
        currency = (request.POST.get('crypto_currency')).upper()
        symbol = request.POST.get('symbol')
        analysis_time = request.POST.getlist('analysis_time')

        candle_content = [request.POST.get('content_1M'), request.POST.get('content_1W'), request.POST.get('content_1D'), request.POST.get('content_4H'), request.POST.get('content_1H'), request.POST.get('content_15m')]

        transaction_content = request.POST.get('transaction_content')
        entry_price = request.POST.get('entry_price')
        tp = request.POST.get('tp')
        sl = request.POST.get('sl')
        amount = request.POST.get('amount')

        img_content = [request.FILES.getlist('img_1M'), request.FILES.getlist('img_1W'), request.FILES.getlist('img_1D'), request.FILES.getlist('img_4H'), request.FILES.getlist('img_1H'), request.FILES.getlist('img_15m')]

        #form = AnswerForm(request.POST)
        #if form.is_valid():
        #    answer = form.save(commit=False)
        #    answer.create_date = timezone.now()
        #    answer.question = question
        #    answer.save()
        #    return redirect(':detail', question_id=question.id)
    #else:
    #    return render(request, 'trading_journal/create.html')

    context = {
               'currency': currency,
               'symbol': symbol,
               'analysis_time': analysis_time,
              }
    
    return render(request, 'trading_journal/create.html', context)

templates/trading_journal/create.html
{% extends "base.html" %}
{% block content %}
<h2 class="p-3 text-white mx-1 my-1 px-5" style="margin-bottom:0px; background-color:black; border: 1px solid black; border-radius: 15px;">Trading Jouranl</h2>

<form class="h-100" enctype="multipart/form-data" method="post" action="{% url 'trading_journal:create' user.pk %}">
  <div class="container my-5 p-0">
  {% csrf_token %}
  {% include "form_errors.html" %}
    <div class="input-group m-3">
      <span class="input-group-text text-white bg-secondary" for="crypto_currency">거래소</span>
      <select name="crypto_currency" id="crypto_currency" class="form-select text-white bg-dark" aria-label="Default select example">
        <option value="BINANCE" {% if currency == "BINANCE" %} selected {% endif %}>Binance</option>
        <option value="BYBIT" {% if currency == "BYBIT" %} selected {% endif %} >Bybit</option>
      </select>

      <span class="input-group-text text-white bg-secondary" for="symbol">거래 코인</span>
      <select name="symbol" id="symbol" class="form-select text-white bg-dark" aria-label="Default select example">
        <option value="BTCUSDT" {% if symbol == "BTCUSDT" %} selected {% endif %}>BTCUSDT</option>
        <option value="ETHUSDT" {% if symbol == "ETHUSDT" %} selected {% endif %}>ETHUSDT</option>
      </select>
      <button id="btn" type="submit" class="btn btn-primary">확인</button>
    </div>
    {% if symbol and currency  %}
      <div class="input-group m-3 w-100">
        <span class="input-group-text text-white bg-secondary">분석 시간</span>
        <span class="input-group-text text-white bg-secondary"><input class="mx-1" type='checkbox' name='analysis_time' value='1M' {% for analysis in analysis_time %} {% if analysis == "1M" %} checked {% endif %} {% endfor %}>1M</span>
        <span class="input-group-text text-white bg-secondary"><input class="mx-1" type='checkbox' name='analysis_time' value='1W' {% for analysis in analysis_time %} {% if analysis == "1W" %} checked {% endif %} {% endfor %}>1W</span>
        <span class="input-group-text text-white bg-secondary"><input class="mx-1" type='checkbox' name='analysis_time' value='1D' {% for analysis in analysis_time %} {% if analysis == "1D" %} checked {% endif %} {% endfor %}>1D</span>
        <span class="input-group-text text-white bg-secondary"><input class="mx-1" type='checkbox' name='analysis_time' value='4H' {% for analysis in analysis_time %} {% if analysis == "4H" %} checked {% endif %} {% endfor %}>4H</span>
        <span class="input-group-text text-white bg-secondary"><input class="mx-1" type='checkbox' name='analysis_time' value='1H' {% for analysis in analysis_time %} {% if analysis == "1H" %} checked {% endif %} {% endfor %}>1H</span>
        <span class="input-group-text text-white bg-secondary"><input class="mx-1" type='checkbox' name='analysis_time' value='15m' {% for analysis in analysis_time %} {% if analysis == "15m" %} checked {% endif %} {% endfor %}>15m</span>
        <button id="btn" type="submit" class="btn btn-primary">확인</button>
      </div>
    {% endif %}
  </div>
  {% if symbol and currency %}
  <div class="container-fluid my-3">
    <div class="row">
      <div class="col">
        {% include "advanced_chart.html" %}
      </div>
      <div class="col-5">
        {% if analysis_time|length != 0 %}
          {% for analysis in analysis_time %}
            <h4 class="mb-0 mt-3">{{analysis}}</h4>
            <div class="row p-0 mx-2">
              <textarea class="col-8" type="text" name="content_{{analysis}}" style="height:100px"></textarea>
              <input class="col" type = "file" accept = "image/*" name="img_{{analysis}}">
            </div>
          {% endfor %}
        {% endif %}
      </div>
    </div>
    {% endif %}
  </div>

  {% if symbol and currency %}
  <div class="container my-3">
    <h4 class="mb-0 mt-3">분석</h4>
    <textarea class="mx-3" type="text" name="transaction_content" style="height:100px; width:100%;"></textarea>

    <div class="input-group m-3 w-100">
      <span class="input-group-text text-white bg-secondary">진입가</span>
      <input class="form-control" type="text" name="entry_price">
      <span class="input-group-text text-white bg-secondary">TP</span>
      <input class="form-control" type="text" name="tp">
      <span class="input-group-text text-white bg-secondary">SL</span>
      <input class="form-control" type="text" name="sl">
      <span class="input-group-text text-white bg-secondary">진입 물량</span>
      <input class="form-control" type="text" name="amount">
    </div>
    <button id="btn" type="submit" class="btn btn-primary m-3" style="float:right;">작성하기</button>
  </div>
  {% endif %}
</form>


{% endblock %}

templates/trading_journal/home.html
{% extends "base.html" %}
{% block content %}
<h2 class="p-3 text-white mx-1 my-1 px-5" style="margin-bottom:0px; background-color:black; border: 1px solid black; border-radius: 15px;">Trading Jouranl</h2>
<div class="container my-2 p-0 h-100">
</div>

{% endblock %}

templates/trading_journal/trading_journal.html
{% extends "base.html" %}
{% block content %}
<h2 class="p-3 text-white mx-1 my-1 px-5" style="margin-bottom:0px; background-color:black; border: 1px solid black; border-radius: 15px;">Trading Jouranl</h2>
<div class="container my-2 p-0 h-100">
  <button type="button" class="btn btn-primary" onclick="location.href='{% url 'trading_journal:create' user.pk %}'">작성하기</button>
</div>

{% endblock %}