config/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('account/', include('account.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
    path('analysis/', include('analysis.urls')),
    path('trading_journal/',include('trading_journal.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('qna/',views.qna, name='qna'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/',views.question_create, name='question_create'),
#    path('trade_history/',views.trade_history, name='trade_history'),
#    path('trade_history/trade/',views.trade, name='trade')
]

pybo/models.py
from django.db import models
#from account.models import Crypto

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

#class TradeHistory(models.Model):
#    crypto = models.ForeignKey(Crypto, on_delete=models.CASCADE)
#    symbol = models.CharField(max_length=100)
#    open_time = models.DateTimeField()
#    open_timestamp = models.PositiveBigIntegerField()
#    close_time = models.DateTimeField()
#    close_timestamp = models.PositiveBigIntegerField()
#    side = models.CharField(max_length=10)
#    leverage = models.IntegerField(null=True,blank=True)
#    open_amount = models.FloatField()
#    close_amount = models.FloatField()
#    open_price = models.FloatField()
#    close_price = models.FloatField()
#    open_cost = models.FloatField()
#    close_cost = models.FloatField()
#    tp = models.FloatField(null=True,blank=True)
#    sl = models.FloatField(null=True,blank=True)
#    open_commission_fee = models.FloatField()
#    close_commission_fee = models.FloatField()
#    funding_fee = models.FloatField()
#    insurance_clear = models.FloatField()
#    realized_pnl = models.FloatField()
#    pnl = models.FloatField()
#    pnl_percentage = models.FloatField()
#    open_balance = models.FloatField()
#    close_balance = models.FloatField()

pybo/forms.py
from django import forms
from pybo.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성
        labels = {
            'subject': '제목',
            'content': '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

#class TradeHistoryFrom(forms.ModelForm):
#    class Meta:
#        model = TradeHistory
#        fields = [
#                  'crypto',
#                  'symbol',
#                  'open_time',
#                  'open_timestamp',
#                  'close_time',
#                  'close_timestamp',
#                  'side',
#                  'leverage',
#                  'open_amount',
#                  'close_amount',
#                  'open_price',
#                  'close_price',
#                  'open_cost',
#                  'close_cost',
#                  'tp',
#                  'sl',
#                  'open_commission_fee',
#                  'close_commission_fee',
#                  'funding_fee',
#                  'insurance_clear',
#                  'realized_pnl',
#                  'pnl',
#                  'pnl_percentage',
#                  'open_balance',
#                  'close_balance',
#                 ]

pybo/views.py
from django.http import HttpResponseNotAllowed
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .forms import QuestionForm, AnswerForm
from .models import Question

from pybo.trade import *

from datetime import datetime
import time

def qna(request):
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list}
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)


def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)


def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

#def trade(request):
#    entry_url=request.GET['url_catch']
#    print("Hello",entry_url)
#    return render(request, 'pybo/trade_history.html')

#def trade_history(request):
#    crypto_list = Crypto.objects.values().filter(user_id=request.user.pk)
#    trade_history_list = TradeHistory.objects.values().filter(crypto_id = crypto_list[0]['id'])
#    if len(trade_history_list)!=0:
#        start_end_date=[str(trade_history_list[0]['open_time']), str(trade_history_list[len(trade_history_list)-1]['open_time'])]
#    else:
#        start_end_date=list()

#    if request.method == 'POST':
#        start_end_date = [request.POST.get('start_date'),request.POST.get('end_date')]
#        start_date = datetime.strptime(start_end_date[0]+" 00:00:00.0000", '%Y-%m-%d %H:%M:%S.%f')
#        end_date = datetime.strptime(start_end_date[1]+" 00:00:00.0000", '%Y-%m-%d %H:%M:%S.%f')
#        trade_history_list = trade_history_list.values().filter(open_time__gte = start_date).filter(close_time__lte = end_date)
#        context = {
#            'crypto_list':crypto_list,
#            'trade_history_list ':trade_history_list ,
#            'start_end_date':start_end_date,
#            'select_id':int(request.POST.get('crypto_currency'))
#        }
#        return render(request, 'pybo/trade_history.html', context)
#    else:
#        form = CryptoForm()
#    context = {
#        'form':form,
#        "crypto_list":crypto_list,
#        'start_end_date':start_end_date,
#    }
#    return render(request, 'pybo/trade_history.html',context)

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}

    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>

{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>
                {{ forloop.counter }}
            </td>
            <td>
                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}