account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('update/<int:pk>/', views.crypto_update, name='update'),
    path('create/', views.crypto_create, name='create'),
    path('create/setting', views.crypto_setting, name='setting'),
    path('delete/<int:pk>/', views.crypto_delete, name='delete'),
]

analysis/urls.py
from django.urls import path

from . import views

app_name = 'analysis'

urlpatterns = [
    path('open_positions',views.open_positions, name='open_positions'),
    path('open_positions/live',views.live_positions, name='live_positions'),
    path('summary',views.summary, name='summary'),
    path('trade_history',views.trade_history, name='trade_history'),
    path('pnl',views.pnl, name='pnl'),
    #path('trade_history/trade/',views.trade, name='trade')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('account/', include('account.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
    path('analysis/', include('analysis.urls')),
    path('trading_journal/',include('trading_journal.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('qna/',views.qna, name='qna'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/',views.question_create, name='question_create'),
#    path('trade_history/',views.trade_history, name='trade_history'),
#    path('trade_history/trade/',views.trade, name='trade')
]

trading_journal/urls.py
from django.urls import path

from . import views

app_name = 'trading_journal'

urlpatterns = [
    path('', views.home, name='home'),
    path('<int:pk>/', views.trading_journal, name='trading_journal'),
    path('<int:pk>/create/', views.create_journal, name='create'),
]

templates/advanced_chart.html
    <div class="tradingview-widget-container">
      <div class="tradingview-widget-container__widget"></div>
      <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-advanced-chart.js" async>
      {
      "width": "100%",
      "height": "900",
      "symbol": "{{currency}}:{{symbol}}.P",
      "interval": "D",
      "timezone": "Asia/Seoul",
      "theme": "dark",
      "style": "1",
      "locale": "kr",
      "hide_side_toolbar": false,
      "allow_symbol_change": true,
      "calendar": false,
      "studies": [
        "STD;EMA",
        "STD;EMA",
        "STD;EMA",
        "STD;MACD",
        "STD;RSI",
        "Volume@tv-basicstudies"
      ],
      "hide_volume": true,
      "support_host": "https://www.tradingview.com"
      }
      </script>
    </div>

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko" style="height: 100%; margin: 0;">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>One More Coin</title>
    <style type="text/css">
        body { font-family:'Arial';}
    </style>
</head>
<body class="bg-dark text-white" style="margin: 0;">
<!-- 네비게이션바 -->
{% include "navbar.html" %}
{% include "ticker_tape_widget.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}

<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<div id="loading" class="fixed-top" style="width: 100%; height: 100%; top: 0; left: 0; position: fixed; display: none; background: #ededed; opacity: 0.7; z-index: 99; text-align: center;">
  <div id="loading_bar" style=" position: absolute; top: 50%; left: 50%; z-index: 100; transform : translate(-50%, -50%);">
    <img src="/static/image/loading.gif" alt="Loading..." />
  </div>
</div>

{% include "footer.html" %}

<script src="{% static 'bootstrap.min.js' %}"></script>
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script>
    
        $('#loading').show();
        
        $(window).on('load', function() {
            $('#loading').hide();
        });
        
        
        /** 
        $(document).ready( function() {
            console.log("finish")
        });
        */
</script>
</body>
</html>

templates/economic_calendar.html
<div>
{% if calendar_lists %}
  {% for calendar_list in calendar_lists %}
      <p>{{calendar_list.scheduled_time| date:"Y-m-d(D) A h시 i분" }} {{calendar_list.contents}}</p>
  {% endfor %}
{% endif %}
</div>

templates/footer.html
<div class="container">
  <footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top">
    <div class="col mb-3">
      <a href="/" class="d-flex align-items-center mb-3 link-body-emphasis text-decoration-none text-white">
        <h4>One More Coin</h4>
      </a>
      <p class="text-secondary">&copy; 2024</p>
    </div>

    <div class="col mb-3">

    </div>

    <div class="col mb-3">
      <h5>Section</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">About</a></li>
      </ul>
    </div>

    <div class="col mb-3">
      <h5>Section</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">About</a></li>
      </ul>
    </div>

    <div class="col mb-3">
      <h5>Section</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">About</a></li>
      </ul>
    </div>
  </footer>
</div>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
  <header class="p-3 text-bg-dark">
    <div class="container-fluid">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-5 link-body-emphasis text-decoration-none">
          <span class="fs-4 text-white">One More Coin</span>
        </a>
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="/" {% if request.path == "/" %} class="nav-link px-2 text-secondary" {% else %} class="nav-link px-2 text-white" {% endif %} >Home</a></li>
          <li><a href="{%url 'analysis:open_positions' %}"{% if request.path|slice:"1:9" == "analysis" %} class="nav-link px-2 text-secondary" {% else %} class="nav-link px-2 text-white" {% endif %} >Analysis</a></li>
          <li><a {% if user.pk %} href="{% url 'trading_journal:trading_journal' user.pk %}" {% else %} href="{% url 'trading_journal:home' %}" {% endif %} {% if request.path|slice:"1:16" == "trading_journal" %} class="nav-link px-2 text-secondary" {% else %} class="nav-link px-2 text-white" {% endif %}>Trading Journal</a></li>
          <li><a href="{%url 'pybo:qna' %}" {% if request.path|slice:"1:5" == "pybo" %} class="nav-link px-2 text-secondary" {% else %} class="nav-link px-2 text-white" {% endif %} >FAQs</a></li>
          <li><a href="#" class="nav-link px-2 text-white">About</a></li>
        </ul>
        <div class="text-end">
          {% if user.is_authenticated %}
          <a  href="{%url 'account:detail' user.pk %}" style = "display:inline;" class="nav-link px-2 text-white">{{user.nickname}} ({{user.email}})</a>
          <button type="button" class="btn btn-outline-light me-2" onclick="location.href= '{% url 'account:logout' %}'">Logout</button>
          {% else %}
          <button type="button" class="btn btn-outline-light me-2" onclick="location.href= '{% url 'account:login' %}'">Login</button>
          <button type="button" class="btn btn-warning" onclick="location.href= '{% url 'account:signup' %}'">Sign-up</button>
          {% endif %}
        </div>
      </div>
    </div>
  </header>

templates/select_currency.html
<div class="input-group mb-3" style="width:40%;">
        <label class="input-group-text text-white bg-secondary" for="crypto_currency">Cryptocurrency exchange</label>
        <select name="crypto_currency" id="crypto_currency" class="form-select text-white bg-secondary" aria-label="Default select example">
            {% for crypto in crypto_list %}
            <option value={{crypto.id}} {% if crypto.id == select_id %} selected {% endif %} >  {{crypto.crypto_currency}}: {{crypto.api_name}}</option>
            {% endfor %}
        </select>
</div>

templates/select_currency_button.html
<div style="float:right">
     <button id="btn" type="submit" class="btn btn-primary">select</button>
</div>

templates/sidebar.html
<div class="d-flex flex-column flex-shrink-0 p-2 text-white bg-dark border-end border-secondary" style="width: 15%; float:left;">
    <ul class="nav nav-pills flex-column mb-auto">

      <li>
        <a href="{%url 'analysis:open_positions' %}" {% if request.path == "/analysis/open_positions" %} class="nav-link active" aria-current="page" {% else %} class="nav-link text-white" {% endif %}>
          <svg class="bi me-2" width="16" height="16"><use xlink:href="{%url 'analysis:open_positions' %}"/></svg>
          Open Positions
        </a>
      </li>
      <li>
        <a href="{%url 'analysis:summary' %}" {% if request.path == "/analysis/summary" %} class="nav-link active" aria-current="page" {% else %} class="nav-link text-white" {% endif %}>
          <svg class="bi me-2" width="16" height="16"><use xlink:href="{%url 'analysis:summary' %}"/></svg>
          Summary
        </a>
      </li>
      <li class="nav-item">
        <a href="{%url 'analysis:trade_history' %}" {% if request.path == "/analysis/trade_history" %} class="nav-link active" aria-current="page" {% else %} class="nav-link text-white" {% endif %}>
          <svg class="bi me-2" width="16" height="16"><use xlink:href="{%url 'analysis:trade_history' %}"/></svg>
          Trade History
        </a>
      </li>
      <li>
        <a href="{%url 'analysis:pnl' %}" {% if request.path == "/analysis/pnl" %} class="nav-link active" aria-current="page" {% else %} class="nav-link text-white" {% endif %}>
          <svg class="bi me-2" width="16" height="16"><use xlink:href="{%url 'analysis:pnl' %}"/></svg>
          PNL
        </a>
      </li>
    </ul>
</div>

templates/symbol_overview.html
<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
  <div class="tradingview-widget-container__widget"></div>
  <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-symbol-overview.js" async>
  {
  "symbols": [
    [
      "NASDAQ",
      "NASDAQ:IXIC|1D"
    ],
    [
     "S&P 500 Index",
     "FOREXCOM:SPXUSD|1D"
    ]
  ],
  "chartOnly": false,
  "width": "90%",
  "height": "50%",
  "locale": "kr",
  "colorTheme": "dark",
  "autosize": true,
  "showVolume": false,
  "showMA": false,
  "hideDateRanges": false,
  "hideMarketStatus": false,
  "hideSymbolLogo": false,
  "scalePosition": "right",
  "scaleMode": "Normal",
  "fontFamily": "-apple-system, BlinkMacSystemFont, Trebuchet MS, Roboto, Ubuntu, sans-serif",
  "fontSize": "10",
  "noTimeScale": false,
  "valuesTracking": "1",
  "changeMode": "price-and-percent",
  "chartType": "area",
  "maLineColor": "#2962FF",
  "maLineWidth": 1,
  "maLength": 9,
  "lineWidth": 2,
  "lineType": 0,
  "dateRanges": [
    "1d|1",
    "1m|30",
    "3m|60",
    "12m|1D",
    "60m|1W",
    "all|1M"
  ]
}
  </script>
</div>
<!-- TradingView Widget END -->

templates/ticker_tape_widget.html
<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
  <div class="tradingview-widget-container__widget"></div>
  <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-ticker-tape.js" async>
  {
  "symbols": [
    {
      "proName": "FOREXCOM:SPXUSD",
      "title": "S&P 500 Index"
    },
    {
      "description": "NASDAQ",
      "proName": "NASDAQ:IXIC"
    },
    {
      "description": "",
      "proName": "COINBASE:BTCUSD"
    },
    {
      "description": "",
      "proName": "COINBASE:ETHUSD"
    },
    {
      "description": "",
      "proName": "FX_IDC:USDKRW"
    }
  ],
  "showSymbolLogo": true,
  "isTransparent": false,
  "displayMode": "adaptive",
  "colorTheme": "dark",
  "locale": "kr"
}
  </script>
</div>
<!-- TradingView Widget END -->

templates/top_currencies.html
<iframe src="https://www.widgets.investing.com/top-cryptocurrencies?theme=darkTheme&roundedCorners=true&cols=symbol,priceUsd,chg24,chg7" width="100%" height="50%" frameborder="0" allowtransparency="true" marginwidth="0" marginheight="0"></iframe>